require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeetupEventsController do

  # This should return the minimal set of attributes required to create a valid
  # MeetupEvent. As you add validations to MeetupEvent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all meetup_events as @meetup_events" do
      meetup_event = MeetupEvent.create! valid_attributes
      get :index
      assigns(:meetup_events).should eq([meetup_event])
    end
  end

  describe "GET show" do
    it "assigns the requested meetup_event as @meetup_event" do
      meetup_event = MeetupEvent.create! valid_attributes
      get :show, :id => meetup_event.id.to_s
      assigns(:meetup_event).should eq(meetup_event)
    end
  end

  describe "GET new" do
    it "assigns a new meetup_event as @meetup_event" do
      get :new
      assigns(:meetup_event).should be_a_new(MeetupEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested meetup_event as @meetup_event" do
      meetup_event = MeetupEvent.create! valid_attributes
      get :edit, :id => meetup_event.id.to_s
      assigns(:meetup_event).should eq(meetup_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MeetupEvent" do
        expect {
          post :create, :meetup_event => valid_attributes
        }.to change(MeetupEvent, :count).by(1)
      end

      it "assigns a newly created meetup_event as @meetup_event" do
        post :create, :meetup_event => valid_attributes
        assigns(:meetup_event).should be_a(MeetupEvent)
        assigns(:meetup_event).should be_persisted
      end

      it "redirects to the created meetup_event" do
        post :create, :meetup_event => valid_attributes
        response.should redirect_to(MeetupEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meetup_event as @meetup_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetupEvent.any_instance.stub(:save).and_return(false)
        post :create, :meetup_event => {}
        assigns(:meetup_event).should be_a_new(MeetupEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetupEvent.any_instance.stub(:save).and_return(false)
        post :create, :meetup_event => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested meetup_event" do
        meetup_event = MeetupEvent.create! valid_attributes
        # Assuming there are no other meetup_events in the database, this
        # specifies that the MeetupEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MeetupEvent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => meetup_event.id, :meetup_event => {'these' => 'params'}
      end

      it "assigns the requested meetup_event as @meetup_event" do
        meetup_event = MeetupEvent.create! valid_attributes
        put :update, :id => meetup_event.id, :meetup_event => valid_attributes
        assigns(:meetup_event).should eq(meetup_event)
      end

      it "redirects to the meetup_event" do
        meetup_event = MeetupEvent.create! valid_attributes
        put :update, :id => meetup_event.id, :meetup_event => valid_attributes
        response.should redirect_to(meetup_event)
      end
    end

    describe "with invalid params" do
      it "assigns the meetup_event as @meetup_event" do
        meetup_event = MeetupEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetupEvent.any_instance.stub(:save).and_return(false)
        put :update, :id => meetup_event.id.to_s, :meetup_event => {}
        assigns(:meetup_event).should eq(meetup_event)
      end

      it "re-renders the 'edit' template" do
        meetup_event = MeetupEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetupEvent.any_instance.stub(:save).and_return(false)
        put :update, :id => meetup_event.id.to_s, :meetup_event => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meetup_event" do
      meetup_event = MeetupEvent.create! valid_attributes
      expect {
        delete :destroy, :id => meetup_event.id.to_s
      }.to change(MeetupEvent, :count).by(-1)
    end

    it "redirects to the meetup_events list" do
      meetup_event = MeetupEvent.create! valid_attributes
      delete :destroy, :id => meetup_event.id.to_s
      response.should redirect_to(meetup_events_url)
    end
  end

end
